// <auto-generated />
using CIS174_OlympicGame.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CIS174_OlympicGame.Migrations
{
    [DbContext(typeof(GameContext))]
    [Migration("20250719004112_addingMigration")]
    partial class addingMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CIS174_OlympicGame.Models.Country", b =>
                {
                    b.Property<string>("CountryID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("GameID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LogoImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SportTypeID")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("CountryID");

                    b.HasIndex("GameID");

                    b.HasIndex("SportTypeID");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            CountryID = "ari",
                            LogoImage = "ARI.png",
                            Name = "Arizona Cardinals"
                        },
                        new
                        {
                            CountryID = "atl",
                            LogoImage = "ATL.png",
                            Name = "Atlanta Falcons"
                        },
                        new
                        {
                            CountryID = "bal",
                            LogoImage = "BAL.png",
                            Name = "Baltimore Ravens"
                        },
                        new
                        {
                            CountryID = "buf",
                            LogoImage = "BUF.png",
                            Name = "Buffalo Bills"
                        },
                        new
                        {
                            CountryID = "car",
                            LogoImage = "CAR.png",
                            Name = "Carolina Panthers"
                        },
                        new
                        {
                            CountryID = "chi",
                            LogoImage = "CHI.png",
                            Name = "Chicago Bears"
                        },
                        new
                        {
                            CountryID = "cin",
                            LogoImage = "CIN.png",
                            Name = "Cincinnati Bengals"
                        },
                        new
                        {
                            CountryID = "cle",
                            LogoImage = "CLE.png",
                            Name = "Cleveland Browns"
                        },
                        new
                        {
                            CountryID = "dal",
                            LogoImage = "DAL.png",
                            Name = "Dallas Cowboys"
                        },
                        new
                        {
                            CountryID = "den",
                            LogoImage = "DEN.png",
                            Name = "Denver Broncos"
                        },
                        new
                        {
                            CountryID = "det",
                            LogoImage = "DET.png",
                            Name = "Detroit Lions"
                        },
                        new
                        {
                            CountryID = "gb",
                            LogoImage = "GB.png",
                            Name = "Green Bay Packers"
                        },
                        new
                        {
                            CountryID = "hou",
                            LogoImage = "HOU.png",
                            Name = "Houston Texans"
                        },
                        new
                        {
                            CountryID = "ind",
                            LogoImage = "IND.png",
                            Name = "Indianapolis Colts"
                        },
                        new
                        {
                            CountryID = "jax",
                            LogoImage = "JAX.png",
                            Name = "Jacksonville Jaguars"
                        },
                        new
                        {
                            CountryID = "kc",
                            LogoImage = "KC.png",
                            Name = "Kansas City Chiefs"
                        },
                        new
                        {
                            CountryID = "lac",
                            LogoImage = "LAC.png",
                            Name = "Los Angeles Chargers"
                        },
                        new
                        {
                            CountryID = "lar",
                            LogoImage = "LAR.png",
                            Name = "Los Angeles Rams"
                        },
                        new
                        {
                            CountryID = "lv",
                            LogoImage = "LV.png",
                            Name = "Las Vegas Raiders"
                        },
                        new
                        {
                            CountryID = "mia",
                            LogoImage = "MIA.png",
                            Name = "Miami Dolphins"
                        },
                        new
                        {
                            CountryID = "min",
                            LogoImage = "MIN.png",
                            Name = "Minnesota Vikings"
                        },
                        new
                        {
                            CountryID = "ne",
                            LogoImage = "NE.png",
                            Name = "New England Patriots"
                        },
                        new
                        {
                            CountryID = "no",
                            LogoImage = "NO.png",
                            Name = "New Orleans Saints"
                        },
                        new
                        {
                            CountryID = "nyg",
                            LogoImage = "NYG.png",
                            Name = "New York Giants"
                        },
                        new
                        {
                            CountryID = "nyj",
                            LogoImage = "NYJ.png",
                            Name = "New York Jets"
                        },
                        new
                        {
                            CountryID = "phi",
                            LogoImage = "PHI.png",
                            Name = "Philadelphia Eagles"
                        },
                        new
                        {
                            CountryID = "pit",
                            LogoImage = "PIT.png",
                            Name = "Pittsburgh Steelers"
                        },
                        new
                        {
                            CountryID = "sea",
                            LogoImage = "SEA.png",
                            Name = "Seattle Seahawks"
                        },
                        new
                        {
                            CountryID = "sf",
                            LogoImage = "SF.png",
                            Name = "San Francisco 49ers"
                        },
                        new
                        {
                            CountryID = "tb",
                            LogoImage = "TB.png",
                            Name = "Tampa Bay Buccaneers"
                        },
                        new
                        {
                            CountryID = "ten",
                            LogoImage = "TEN.png",
                            Name = "Tennessee Titans"
                        },
                        new
                        {
                            CountryID = "was",
                            LogoImage = "WAS.png",
                            Name = "Washington Commanders"
                        });
                });

            modelBuilder.Entity("CIS174_OlympicGame.Models.Game", b =>
                {
                    b.Property<string>("GameID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GameID");

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            GameID = "afc",
                            Name = "AFC"
                        },
                        new
                        {
                            GameID = "nfc",
                            Name = "NFC"
                        });
                });

            modelBuilder.Entity("CIS174_OlympicGame.Models.SportType", b =>
                {
                    b.Property<string>("SportTypeID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SportTypeID");

                    b.ToTable("SportTypes");

                    b.HasData(
                        new
                        {
                            SportTypeID = "north",
                            Name = "North"
                        },
                        new
                        {
                            SportTypeID = "south",
                            Name = "South"
                        },
                        new
                        {
                            SportTypeID = "east",
                            Name = "East"
                        },
                        new
                        {
                            SportTypeID = "west",
                            Name = "West"
                        });
                });

            modelBuilder.Entity("CIS174_OlympicGame.Models.Country", b =>
                {
                    b.HasOne("CIS174_OlympicGame.Models.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameID");

                    b.HasOne("CIS174_OlympicGame.Models.SportType", "SportType")
                        .WithMany()
                        .HasForeignKey("SportTypeID");

                    b.Navigation("Game");

                    b.Navigation("SportType");
                });
#pragma warning restore 612, 618
        }
    }
}
